# Generated by Django 4.2.7 on 2023-12-12 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mybook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_books', models.ManyToManyField(blank=True, related_name='read_books', to='mybook.book')),
                ('to_read_books', models.ManyToManyField(blank=True, related_name='to_read_books', to='mybook.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReadBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybook.book')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybook.usershelf')),
            ],
        ),
    ]
