# Generated by Django 4.2.7 on 2023-12-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0002_rename_userreview_useropinion_book_opinions'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbook',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='readbook',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='opinions',
            field=models.ManyToManyField(related_name='book_opinion', to='mybook.readbook'),
        ),
        migrations.DeleteModel(
            name='UserOpinion',
        ),
    ]
