# Generated by Django 4.2.7 on 2023-12-21 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mybook', '0003_readbook_rating_readbook_review_alter_book_opinions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readbook',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
