# Generated by Django 4.2.7 on 2024-01-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0005_remove_readbook_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='opinions',
            field=models.ManyToManyField(related_name='books_opinion', to='mybook.readbook'),
        ),
    ]
