# Generated by Django 4.2.7 on 2024-01-05 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0007_alter_book_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookOpinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_date', models.DateField(blank=True, null=True)),
                ('review', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='book',
            name='opinions',
        ),
        migrations.DeleteModel(
            name='ReadBook',
        ),
        migrations.AddField(
            model_name='bookopinion',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybook.book'),
        ),
        migrations.AddField(
            model_name='bookopinion',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybook.usershelf'),
        ),
        migrations.AddField(
            model_name='book',
            name='book_opinion',
            field=models.ManyToManyField(related_name='book_opinion', to='mybook.bookopinion'),
        ),
    ]
