# Generated by Django 4.2.7 on 2024-01-05 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0008_bookopinion_remove_book_opinions_delete_readbook_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookopinion',
            old_name='book',
            new_name='book_id',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_opinion',
            field=models.ManyToManyField(to='mybook.bookopinion'),
        ),
    ]
