# Generated by Django 4.2.7 on 2024-01-08 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mybook', '0009_rename_book_bookopinion_book_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookopinion',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_opinion',
        ),
    ]
